[package]
name = "vm-pci"
version = "0.1.0"
authors = ["TODO"]
description = "Crate for emulating PCI devices in Rust hypervisors."
repository = "https://github.com/rust-vmm/vm-pci"
readme = "README.md"
keywords = ["virt"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

[dependencies]
